### ISSUE TITLE
FOUC dark mode

### ISSUE THREAD

**Issue by revolunet** [DISIC/design.numerique.gouv.fr#359]
Bonjour, je me permets de remonter un petit détail, si on a le mode sombre niveau système, on a un petit flash blanc à l'ouverture de la page. 

Au cas où, une SE a fixé le problème de cette façon : https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/9727

Cordialement

**Comment by yaaax** [comment]
Vu après…

Ce snippet suggéré par le DSFR :
https://main--ds-gouv.netlify.app/example/scheme/

Voir [Clignotement au chargement de la page lorsque le dark mode est sélectionné #960](https://github.com/GouvernementFR/dsfr/issues/960)

Pour info @revolunet
