### ISSUE TITLE
Licence libre?

### ISSUE THREAD

**Issue by bzg** [DISIC/design.numerique.gouv.fr#63]
Bonjour, la page https://design.numerique.gouv.fr/misc/accessibilite/ indique que le code source du site est sous licence libre, mais le dépôt ne contient pas de licence.  Je vois dans le README que c'est en cours de réévaluation.

Si je peux aider à répondre à des questions, n'hésitez pas.

**Comment by marineb** [comment]
Salut @bzg ! Oui on avait échangé à ce sujet. On avait retiré la licence à cause de la typographie Marianne. Il me semble que tu m'avais dit que qu'on pouvait remettre la licence et spécifier que Marianne n'était néanmoins pas libre, c'est bien ça ?

**Comment by bzg** [comment]
Oui tout à fait. Vous pouvez dire "Le contenu de ce dépôt est placé sous licence A, à l'exception [des fichiers/du répertoire] X, Y, Z." ou même "Le contenu de ce dépôt est placé sous licence A sauf lorsqu'une licence spécifique est indiquée pour un fichier, auquel cas cette licence spécifique est celle qui prévaut."

Le but est de rester simple et clair.

**Comment by marineb** [comment]
C'est fait. Merci @bzg !

**Comment by cheznewa** [comment]
Bonjour
Mais L'exception (Sauf) Qui Est Bien La Police D'ecriture "Marianne", La On N'a Pas De Licence, Qui Detaille Les Conditions.
