### ISSUE TITLE
[RGAA] Prise de focus non visible sur les CTA sur Firefox

### ISSUE THREAD

**Issue by amezyane** [DISIC/design.numerique.gouv.fr#83]
Sur Firefox, le focus n'est pas visible sur tous les CTA ("Voir les défis", "L'accessibilité en détails", etc.). 

Sur Chrome, la couleur de l'outline est définie par défaut avec `-webkit-focus-ring-color`. 

Sur Firefox, l'outline reprend la couleur du texte dans le lien ou le bouton. Or, le texte est blanc lorsque le lien a le focus. Du coup, l'outline est également blanc et n'est pas visible avec le fond du site.

Pour corriger cela, on peut dans le CSS rajouter une propriété `outline` indiquant la couleur, pour les boutons/liens à l'état `:focus`.

**Comment by benoitdequick** [comment]
corrigé sur la branche RGAA
