### ISSUE TITLE
[RGAA] Design pattern ARIA non correct pour le menu de navigation

### ISSUE THREAD

**Issue by amezyane** [DISIC/design.numerique.gouv.fr#84]
Le design pattern ARIA utilisé pour le menu de navigation ne convient pas (`role=menu` sur le `<ul#menu>`) : 

- Celui-ci est normalement utilisé par exemple pour des barres d'outils dans des applications web ou dans les champs WYSIWYG. 
- Pour respecter le design pattern, les `<li>` enfants devraient avoir un attribut ARIA comme `role=menuitem`. Il devrait être également possible de naviguer entre les liens au clavier avec les flèches haut et bas. 
- Enfin, le `role=navigation` sur la balise parente `<nav>` suffit ici pour indiquer le menu de navigation aux lecteurs d'écran.

**Comment by benoitdequick** [comment]
Corrigé sur la branche RGAA
